[package]
name = "argmin_core"
version = "0.1.0"
authors = ["Stefan Kroboth <stefan.kroboth@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "WIP optimization toolbox for Rust"
documentation = "https://argmin-rs.github.io/argmin-core/argmin_core/"
homepage = "https://github.com/argmin-rs/argmin-core"
repository = "https://github.com/argmin-rs/argmin-core"
readme = "README.md"
keywords = ["optimization", "math", "science", "HPC"]
categories = ["science"]
#license-file = "LICENSE-APACHE"
exclude = [ 
	".travis.yml",
	"push_docs",
]

[dependencies]
failure = "0.1.2"
failure_derive = "0.1.2"
ctrlc = "3.1.1"
slog = "2.4.0"
slog-term = "2.2.4"
slog-async = "2.3.0"
slog-json = "2.2.0"
rand = "0.5.5"

[badges]
travis-ci = { repository = "argmin-rs/argmin-core", branch = "master" }
