[package]
name = "argmin_core"
version = "0.0.0"
authors = ["Stefan Kroboth <stefan.kroboth@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "WIP optimization toolbox for Rust"
documentation = "https://stefan-k.github.io/argmin-rs/argmin-core/"
homepage = "https://github.com/stefan-k/argmin-core"
repository = "https://github.com/stefan-k/argmin-core"
readme = "README.md"
keywords = ["optimization", "math", "science", "HPC"]
categories = ["science"]
#license-file = "LICENSE-APACHE"
exclude = [ 
	".travis.yml",
	"push_docs",
]

[dependencies]
failure = "*"
failure_derive = "*"
ctrlc = "*"
slog = "*"
slog-term = "*"
slog-async = "*"
slog-json = "*"
